---
framework: mocha
preRun:
     command:
        - npm install
preMerge:
  pattern:
    - "./test/**/*-test.js"
postMerge:
  pattern: 
    - "./test/**/*-test.js"
postRun:
     command:
        - node --version
nodeVersion: 17.3.1
version: 1.0
