---
framework: mocha
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./test/**/*-test.js"
postMerge:
  pattern: 
    - "./test/**/*-test.js"
postRun:
     command:
        - yarn --version
nodeVersion: 14.17.0
version: 1.0
